Update README.rst
williamjameshandley/CosmoChord pull request #1
Opened 2020-04-18 20:20 UTC by appetrosyan

Added installation instructions from CosmoMC

2020-04-20 07:12 UTC, williamjameshandley requested changes
Many thanks for this very helpful contribution @appetrosyan. I have a few minor comments/discussion points, and then we can merge this in.

2020-04-20 07:12 UTC, williamjameshandley commented on README.rst
> +As this is a fork of CosmoMC the process of installing the Planck lieklihoods is identical:
lieklihoods -> likelihoods

2020-04-20 07:12 UTC, williamjameshandley commented on README.rst
> +   sudo pacman -S cfitsio
Here I think it's probably best to say '(you may need) to install cfitsio if the `--install_all_deps` later on is unable to', and simply have a list of prerequisites, rather than presupposing an arch-based distribution (or the use of pip for installing python packages).

2020-04-20 07:12 UTC, williamjameshandley commented on README.rst
> +- Obtain from the `Planck Legacy archive <https://wiki.cosmos.esa.int/planck-legacy-archive/index.php/Main_Page>` the following the `COM_Likelihood_Code-*.tar.gz` and `COM-Likelihood_Data-*.tar.gz`.
Is there a direct download link? I seem to remember that cobaya uses one, so this might make the installation even more seamless for new users if they could just click a link to download it (or use curl/wget).

2020-04-20 07:12 UTC, williamjameshandley commented on README.rst
> +   echo echo -e "\nsource $(pwd)/bin/clik_profile.sh" >> ~/.bashrc
Here I think it's probably clearer to simply say  something like 'you need to run the `source bin/clik_profile.sh` each time you want to use the Planck likelihood. If you want to avoid remembering to run this every time, you should put it into your bashrc`. I personally don't have it in my bashrc, but that's because I have had to use multiple planck likelihoods in the past, and generally tend to work in virtual environments to avoid cluttering the PATH with potentially contradictory setups.

2020-04-20 14:41 UTC, appetrosyan commented on README.rst
> +   sudo pacman -S cfitsio
It almost always breaks. --install_all_deps wasn't updated, so it's hardcoded to download versions that are no longer supported and no longer exist.

2020-04-20 14:49 UTC, appetrosyan commented on README.rst
> +- Obtain from the `Planck Legacy archive <https://wiki.cosmos.esa.int/planck-legacy-archive/index.php/Main_Page>` the following the `COM_Likelihood_Code-*.tar.gz` and `COM-Likelihood_Data-*.tar.gz`.
These links break often. I'd be hesitant.

2020-04-20 14:52 UTC, appetrosyan commented on README.rst
> +   echo echo -e "\nsource $(pwd)/bin/clik_profile.sh" >> ~/.bashrc
It breaks on `fish` and `xonsh`. You need to use the same bash-like shell to source as the shell you use to run the commands. Ideally, we should just have `fish` and Python versions of these environment set-up scripts.

2020-04-20 15:00 UTC, williamjameshandley commented
I see. It still is better to provide advice that is python installation (i.e.  
many people use conda, apt or pacman to install python)
and package manager independent. This would also presuppose root access, which 
you don't have for example on a HPC machine.

On Mon, Apr 20, 2020 at 07:42:09AM -0700, Aleksandr Petrosyan wrote:
>@appetrosyan commented on this pull request.
>
>
>
>> +- install prerequisites of Planck Code:
>+.. bash::
>+   pip install cython astropy
>+   sudo pacman -S cfitsio
>
>It almost always breaks. --install_all_deps wasn't updated, so it's hardcoded to download versions that are no longer supported and no longer exist.
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/williamjameshandley/CosmoChord/pull/1#discussion_r411434699

-- 
Dr Will Handley
Research Fellow at Gonville & Caius College

Cavendish Astrophysics Group
Cavendish Laboratory
JJ Thomson Avenue
Cambridge, UK
CB3 0HE

Room K16
Kavli Institute for Cosmology
Cambridge, UK

Tel: +44-(0)1223-764042
Mob: +44-(0)7718-622713
Email: wh260@cam.ac.uk
arXiv papers: https://arxiv.org/a/handley_w_1
GitHub: https://github.com/williamjameshandley
Skype: wjhandley
Website: http://www.kicc.cam.ac.uk/directory/wh260

2020-04-20 15:01 UTC, williamjameshandley commented on README.rst
> +   sudo pacman -S cfitsio
I see. It still is better to provide advice that is python installation (i.e.
many people use conda, apt or pacman to install python)
and package manager independent. This would also presuppose root access, which
you don't have for example on a HPC machine.

2020-04-20 15:02 UTC, williamjameshandley commented on README.rst
> +- Obtain from the `Planck Legacy archive <https://wiki.cosmos.esa.int/planck-legacy-archive/index.php/Main_Page>` the following the `COM_Likelihood_Code-*.tar.gz` and `COM-Likelihood_Data-*.tar.gz`.
It seems to work for cobaya fairly well in my experience. You could always say 'use these links, but if that fails visit the PLA'

2020-04-20 15:03 UTC, williamjameshandley commented on README.rst
> +   echo echo -e "\nsource $(pwd)/bin/clik_profile.sh" >> ~/.bashrc
Also on zsh in my experience, but if you're using those, then you're likely to be able to cope with modifying them as necessary. Surely this is an argument for providing non bash-specific advice?

2020-04-22 08:11 UTC, williamjameshandley requested changes
This is all looking much better. There are a couple of changes that I think would make it easier for users who are newer to linux (which are generally quite strongly correlated with astrophysicists installing software for the first time, which is who a README such as this is primarily targeted at)

2020-04-22 08:11 UTC, williamjameshandley commented on README.rst
> +- install ``cfitsio``. For ArchLinux this is available in the official repositories. On Scientific linux, it's pre-installed and needs to be found with ``module avail`` and loaded with e.g. ``module
I think that this is still too system-specific, and new users are likely to get lost in the detail associated with arch linux (a very small subset of astrophysicists use this), scientific linux (many cluster users  won't actually know what linux distribution their cluster runs on).

To cater to the widest variety of users, it would be better simply to say something like "The prerequisites for the Planck likelihood code are that you have installed the cython and astropy Python modules, and have a working version of cfitsio (I believe if one has installed astropy, then cfitsio should also be working).

2020-04-22 08:11 UTC, williamjameshandley commented on README.rst
> +   echo echo -e "\nsource $(pwd)/bin/clik_profile.sh" >> ~/.bashrc
It would be better to avoid a possibly confusing bash command, and simply say "put the following line in your .bashrc", which then caters to a wider variety of users and abilities.

2021-04-12 14:47 UTC, appetrosyan reviewed
Resolved! Any further changes?

2021-07-10 13:06 UTC, closed without merging